/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace DotNetHack.RPC
{
  public enum BodyRegion
  {
    Head = 0,
    Face = 1,
    Neck = 2,
    Thorax = 3,
    Abdomen = 4,
    Spine = 5,
    UpperExtremity = 6,
    LowerExtremity = 7,
    Other = 8,
  }
}
