/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace DotNetHack.RPC
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class GameState : TBase
  {
    private List<Player> _players;
    private List<NPC> _npcs;
    private List<Message> _broadcast;

    public List<Player> Players
    {
      get
      {
        return _players;
      }
      set
      {
        __isset.players = true;
        this._players = value;
      }
    }

    public List<NPC> Npcs
    {
      get
      {
        return _npcs;
      }
      set
      {
        __isset.npcs = true;
        this._npcs = value;
      }
    }

    public List<Message> Broadcast
    {
      get
      {
        return _broadcast;
      }
      set
      {
        __isset.broadcast = true;
        this._broadcast = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool players;
      public bool npcs;
      public bool broadcast;
    }

    public GameState() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                Players = new List<Player>();
                TList _list20 = iprot.ReadListBegin();
                for( int _i21 = 0; _i21 < _list20.Count; ++_i21)
                {
                  Player _elem22 = new Player();
                  _elem22 = new Player();
                  _elem22.Read(iprot);
                  Players.Add(_elem22);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                Npcs = new List<NPC>();
                TList _list23 = iprot.ReadListBegin();
                for( int _i24 = 0; _i24 < _list23.Count; ++_i24)
                {
                  NPC _elem25 = new NPC();
                  _elem25 = new NPC();
                  _elem25.Read(iprot);
                  Npcs.Add(_elem25);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.List) {
              {
                Broadcast = new List<Message>();
                TList _list26 = iprot.ReadListBegin();
                for( int _i27 = 0; _i27 < _list26.Count; ++_i27)
                {
                  Message _elem28 = new Message();
                  _elem28 = new Message();
                  _elem28.Read(iprot);
                  Broadcast.Add(_elem28);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("GameState");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Players != null && __isset.players) {
        field.Name = "players";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Players.Count));
          foreach (Player _iter29 in Players)
          {
            _iter29.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (Npcs != null && __isset.npcs) {
        field.Name = "npcs";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Npcs.Count));
          foreach (NPC _iter30 in Npcs)
          {
            _iter30.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (Broadcast != null && __isset.broadcast) {
        field.Name = "broadcast";
        field.Type = TType.List;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Broadcast.Count));
          foreach (Message _iter31 in Broadcast)
          {
            _iter31.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("GameState(");
      sb.Append("Players: ");
      sb.Append(Players);
      sb.Append(",Npcs: ");
      sb.Append(Npcs);
      sb.Append(",Broadcast: ");
      sb.Append(Broadcast);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
