/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace DotNetHack.RPC
{
  public enum InjurySeverityScore
  {
    Minor = 0,
    Moderate = 1,
    Serious = 2,
    Severe = 3,
    Critical = 4,
    Maximal = 5,
  }
}
