/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace DotNetHack.RPC
{
  public enum NPCType
  {
    Monster = 0,
    Villager = 1,
    Shopkeeper = 2,
  }
}
