/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace DotNetHack.RPC
{
  public enum Role
  {
    Archeologist = 0,
    Barbarian = 1,
    Healer = 2,
    Knight = 3,
    Monk = 4,
    Priest = 5,
    Ranger = 6,
    Rogue = 7,
    Samurai = 8,
    Tourist = 9,
    Valkyrie = 10,
    Wizard = 11,
  }
}
