/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace DotNetHack.RPC
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Sound : TBase
  {
    private string _soundFile;
    private int _attenuation;

    public string SoundFile
    {
      get
      {
        return _soundFile;
      }
      set
      {
        __isset.soundFile = true;
        this._soundFile = value;
      }
    }

    public int Attenuation
    {
      get
      {
        return _attenuation;
      }
      set
      {
        __isset.attenuation = true;
        this._attenuation = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool soundFile;
      public bool attenuation;
    }

    public Sound() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              SoundFile = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              Attenuation = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Sound");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (SoundFile != null && __isset.soundFile) {
        field.Name = "soundFile";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(SoundFile);
        oprot.WriteFieldEnd();
      }
      if (__isset.attenuation) {
        field.Name = "attenuation";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Attenuation);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Sound(");
      sb.Append("SoundFile: ");
      sb.Append(SoundFile);
      sb.Append(",Attenuation: ");
      sb.Append(Attenuation);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
