/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


/// <summary>
/// Description: This packet contains a user identifier and some raw data.
/// </summary>
#if !SILVERLIGHT
[Serializable]
#endif
public partial class DNHPacket : TBase
{
  private long _seq;
  private string _RawData;

  public long Seq
  {
    get
    {
      return _seq;
    }
    set
    {
      __isset.seq = true;
      this._seq = value;
    }
  }

  public string RawData
  {
    get
    {
      return _RawData;
    }
    set
    {
      __isset.RawData = true;
      this._RawData = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool seq;
    public bool RawData;
  }

  public DNHPacket() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.I64) {
            Seq = iprot.ReadI64();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 2:
          if (field.Type == TType.String) {
            RawData = iprot.ReadString();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("DNHPacket");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (__isset.seq) {
      field.Name = "seq";
      field.Type = TType.I64;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteI64(Seq);
      oprot.WriteFieldEnd();
    }
    if (RawData != null && __isset.RawData) {
      field.Name = "RawData";
      field.Type = TType.String;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(RawData);
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder sb = new StringBuilder("DNHPacket(");
    sb.Append("Seq: ");
    sb.Append(Seq);
    sb.Append(",RawData: ");
    sb.Append(RawData);
    sb.Append(")");
    return sb.ToString();
  }

}

