/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum ObjectType
{
  ITEM = 0,
  ACTOR = 1,
  PLAYER = 2,
}
