/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace DotNetHack.RPC
{
  public enum Direction
  {
    Left = 0,
    Right = 1,
    Up = 2,
    Down = 3,
  }
}
