/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;

namespace DotNetHack.RPC
{
  public static class dnhConstants
  {
    public static Dictionary<BodyRegion, BodyRegion> BODY_DEPENDENCIES = new Dictionary<BodyRegion, BodyRegion>();
    static dnhConstants()
    {
      BODY_DEPENDENCIES[BodyRegion.LowerExtremity] = BodyRegion.Spine;
      BODY_DEPENDENCIES[BodyRegion.Head] = BodyRegion.Spine;
    }
  }
}
