/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace DotNetHack.RPC
{
  public enum ItemType
  {
    Armor = 0,
    Weapon = 1,
    Scroll = 2,
    Tome = 3,
    Potion = 4,
    Currency = 5,
    Key = 6,
    Tool = 7,
    Food = 8,
    Other = 9,
  }
}
