/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace DotNetHack.RPC
{
  public enum Race
  {
    Human = 0,
    Elf = 1,
    Dwarf = 2,
    Gnome = 3,
    Orc = 4,
  }
}
