/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace DotNetHack.RPC
{
  public enum StatusEffectType
  {
    Blinded = 0,
    Bloodied = 1,
    Dazed = 2,
    Deafened = 3,
    Dying = 4,
    Immobilized = 5,
    Prone = 6,
    Resist = 7,
    Restrained = 8,
    Running = 9,
    Shielded = 10,
    Slowed = 11,
    Stunned = 12,
    Unconscious = 13,
    Vulnerable = 14,
    Concealed = 15,
    Cursed = 16,
    Hidden = 17,
    Invisible = 18,
    Weakened = 19,
  }
}
